# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: http://sunhanbin.com
domain: 
date_format: "ordinal"
title: 一亩三分地
subtitle: "指尖人生 Frank Sun"
description: "指尖人生 Frank Sun"
keywords: 一亩三分地
gavatar: /favicon.ico
favicon: /favicon.ico
header-img: facebook.jpg
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/sunailian/sunailian.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: Frank Sun 
organization: NetEase, Inc.
organization_url: http://www.163.com
location: HangZhou, China
email: sunhanbin@139.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet: 
    extensions: 
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - with_toc_data
        - strikethrough

pygments: true
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
duoshuo_username: sunhanbin
github_username: sunailian
douban_username: sunailian
facebook_username: mzlogin
weibo_username: sunangie@126.com
zhihu_username: sunangie@126.com
twitter_username: mzlogin
#changyan: sunangie
changyan: false

# ---------------- #
#     Defaults     #
# ---------------- #
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "Frank Sun"
            header-img: "facebook.jpg"
            autotoc: true
    -
        scope:
            path: ""
            type: "wiki"
        values:
            autotoc: true

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Python, Design Patterns]
skill_database_app_keywords: [Oracle,MySQL]
popular_repos: ['chinese-copywriting-guidelines','android-reverse-engineering', 'csdncommenter', 'sunailian.github.io', 'vim-markdown-toc']
contribute_repos: ['sparanoid/chinese-copywriting-guidelines', 'waylife/RentCrawer']

# ---------------- #
#      Comments    #
# ---------------- #
comments :
    provider : duoshuo
    duoshuo : 
      short_name : sunhanbin

